package Problem_002;

/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class EvenFibonacci {
    public int fib(int n) {
        if (n < 2) {
            return n;
        }
        else{
            return fib(n - 1) + fib(n - 2);
        }
    }

    public int fibEven(int n) {
        if (n < 2) return 0;
        int result = 0;
        int prev = 0;
        int next = 1;
        int sum = 0;
        for (int i = 2; i < n; i++) {
            result = prev + next;
            prev = next;
            next = result;
            if (result % 2 == 0) {
                sum = result + sum;
            }
            if (sum > n) return sum;
        }
        return sum;
    }
}
